import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="flex justify-center items-center">
        <main className="min-h-screen flex items-center flex-col max-w-sm md:max-w-3xl lg:max-w-full lg:w-full p-4 lg:px-10">
          {children}
        </main>
      </body>
    </html>
  );
}
